version: '3.5'
services:
  soundflyer-db:
    container_name: soundflyer-db
    image: soundflyer-db:${ENV}
    # Mysql 변수들
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306

  soundflyer-back:
    container_name: soundflyer-back
    image: soundflyer-back:${ENV}
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=${ENV}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - soundflyer-db

  nginx:
    container_name: nginx
    image: nginx:${ENV}
    volumes:
      - ./docker/data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/data/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443
    command: sh -c "nginx && tail -f /dev/null"